### ISSUE TITLE
Server events aren't available when OnPlayerReady fires

### ISSUE THREAD

**Issue by emiletrep** [seaofvoices/crosswalk#23]
When OnPlayerReady fires in a Client Module, it isn't actually ready because ServerModules is still an empty table.

Here's a repro:
[crosswalk-bug.zip](https://github.com/seaofvoices/crosswalk/files/12365533/crosswalk-bug.zip)

**Comment by jeparlefrancais** [comment]
Hey 👋 I found out that this happens when their are no remotes defined in the client modules. I'll submit a fix for this as soon as I get done with #22 

Thanks for the repro that helped a lot 👍
